alias vi=vim
#alias exit='clear && exit'
#alias test='cd ~/testflight/web && ./manage.py test account area51 api application device notifications team testflight utils support marketplace feedback flightdeck sdk stickers live'
#alias unfuckbootstrap="launchctl list|grep UIKitApplication|awk '{print $3}'|xargs launchctl remove"
alias tfactivate='source ~/code/virtualenvs/testflight/bin/activate'
alias sdkactivate='source ~/code/virtualenvs/sdk/bin/activate'
alias testactivate='source ~/code/virtualenvs/tests/bin/activate'
alias tfdeploy='~/code/testflight_deploy/bin/tfdeploy'
alias tmux='TERM=rxvt-256color tmux'
alias pep8='python2.7 pep8'
alias cower='cower --color=auto'
#alias grep='grep -n --color=auto'
#alias ls='ls --color=auto'
